services:
  - type: web
    name: dvs-1.2
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
    healthCheckPath: /api/check-init
    autoDeploy: true
    plan: free 